### ISSUE TITLE
Search Result is empty Array

### ISSUE THREAD

**Issue by friederiket** [TheBoringDude/kuryana#1]
Hey,

I cannot seem to make the search work, all I get is an empty array, no matter the search query I use.

**Comment by TheBoringDude** [comment]
Hello, thank you for reporting this problem...

I have committed a fix, can you please check if it is working? 
[https://kuryana.vercel.app/search/q/{yourquery}](https://kuryana.vercel.app/search/q/)

**Comment by friederiket** [comment]
It is working now!
