### ISSUE TITLE
cast?

### ISSUE THREAD

**Issue by fswdevl** [TheBoringDude/kuryana#18]
Hi any plans to add casts to the api?

**Comment by TheBoringDude** [comment]
have plans for this but maybe soon, 

PRs are welcome

**Comment by sujalgoel** [comment]
the cast function has been added https://github.com/TheBoringDude/kuryana/blob/master/api/fetch.py#L39

**Comment by TheBoringDude** [comment]
> Hi any plans to add casts to the api?

Hello, I have added new endpoints: 
- For getting the drama/movie casts
    - `https://kuryana.vercel.app/id/{mydramalist-slug}/cast`
- For getting details about a person?
    - `https://kuryana.vercel.app/people/{people-id}`

can you please check if it fits your needs?

**Comment by fswdevl** [comment]
This is exactly what I was looking for. Thank you for implementing it.
