### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by imDivu** [TheBoringDude/kuryana#20]
> [Example Link](https://kuryana.vercel.app/id/65743-alien-girl-chai-xiao-qi-2) 

> Sometime I Got [ValueError](https://github.com/TheBoringDude/kuryana/blob/a105f737dd8496688d41f99733ef39a12598f4a5/api/fetch.py#L26)  

`File "/var/task/api/fetch.py", line 81, in _get
    self._get_main_container()
  File "/var/task/api/fetch.py", line 27, in _get_main_container
    (container.find("div", class_="col-film-rating").find("div").text)
ValueError: could not convert string to float: 'N/A'`

**Comment by TheBoringDude** [comment]
will check on this, ..

**Comment by TheBoringDude** [comment]
> > [Example Link](https://kuryana.vercel.app/id/65743-alien-girl-chai-xiao-qi-2)
> 
> > Sometime I Got [ValueError](https://github.com/TheBoringDude/kuryana/blob/a105f737dd8496688d41f99733ef39a12598f4a5/api/fetch.py#L26)
> 
> `File "/var/task/api/fetch.py", line 81, in _get self._get_main_container() File "/var/task/api/fetch.py", line 27, in _get_main_container (container.find("div", class_="col-film-rating").find("div").text) ValueError: could not convert string to float: 'N/A'`

hi, can you please check if it has been fixed

**Comment by imDivu** [comment]
> > > [Example Link](https://kuryana.vercel.app/id/65743-alien-girl-chai-xiao-qi-2)
> > 
> > 
> > > Sometime I Got [ValueError](https://github.com/TheBoringDude/kuryana/blob/a105f737dd8496688d41f99733ef39a12598f4a5/api/fetch.py#L26)
> > 
> > 
> > `File "/var/task/api/fetch.py", line 81, in _get self._get_main_container() File "/var/task/api/fetch.py", line 27, in _get_main_container (container.find("div", class_="col-film-rating").find("div").text) ValueError: could not convert string to float: 'N/A'`
> 
> hi, can you please check if it has been fixed

Ok, I'ii Try 😉

**Comment by imDivu** [comment]
@imDivu

**Comment by imDivu** [comment]
> > > [Example Link](https://kuryana.vercel.app/id/65743-alien-girl-chai-xiao-qi-2)
> > 
> > 
> > > Sometime I Got [ValueError](https://github.com/TheBoringDude/kuryana/blob/a105f737dd8496688d41f99733ef39a12598f4a5/api/fetch.py#L26)
> > 
> > 
> > `File "/var/task/api/fetch.py", line 81, in _get self._get_main_container() File "/var/task/api/fetch.py", line 27, in _get_main_container (container.find("div", class_="col-film-rating").find("div").text) ValueError: could not convert string to float: 'N/A'`
> 
> hi, can you please check if it has been fixed

Done! It's Working Well
