### ISSUE TITLE
Error 404 on ID Search - But fixed by a couple of refreshes

### ISSUE THREAD

**Issue by ajimoji** [TheBoringDude/kuryana#3]
I noticed that if I call a particular id/slug, it sometimes returns an error 404. However, after 5 or so refreshes, the call proceeds successfully. 

Does this have something to do with cloudflare?

Tried it with: [this](https://kuryana.vercel.app/id/681629-back-to-the-2008) and [this](https://kuryana.vercel.app/id/58953-mouse)

**Comment by TheBoringDude** [comment]
Thank you for reporting this issue. I am not sure what causes it, I will try to investigate this first.

**Comment by TheBoringDude** [comment]
> I noticed that if I call a particular id/slug, it sometimes returns an error 404. However, after 5 or so refreshes, the call proceeds successfully.
> 
> Does this have something to do with cloudflare?
> 
> Tried it with: [this](https://kuryana.vercel.app/id/681629-back-to-the-2008) and [this](https://kuryana.vercel.app/id/58953-mouse)

I have pushed a fix, can you please check if it is working for you or not?

**Comment by ajimoji** [comment]
It does. Perfectly! Thanks so much. :)
